// // RobotBuilder Version: 5.0
// //
// // This file was generated by RobotBuilder. It contains sections of
// // code that are automatically generated and assigned by robotbuilder.
// // These sections will be updated in the future when you export to
// // Java from RobotBuilder. Do not put any code or make any change in
// // the blocks indicating autogenerated code or it will be lost on an
// // update. Deleting the comments indicating the section will prevent
// // it from being updated in the future.

// // ROBOTBUILDER TYPE: Command.

// package frc.robot.commands;
// import edu.wpi.first.math.kinematics.ChassisSpeeds;
// import edu.wpi.first.math.kinematics.DifferentialDriveKinematics;
// import edu.wpi.first.math.kinematics.DifferentialDriveWheelSpeeds;
// import edu.wpi.first.wpilibj2.command.CommandBase;
// import java.util.function.DoubleSupplier;

// import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

// // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
// import frc.robot.subsystems.TankDrive;

// // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// /**
//  *
//  */
// public class Drive extends CommandBase {

//     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
//         private final TankDrive m_tankDrive;
//     private double m_leftPerc;
//     private double m_rightPerc;
 
//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

//     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


//     public Drive(double leftPerc, double rightPerc, TankDrive subsystem) {

//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
//         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
//         m_leftPerc = leftPerc;
//         m_rightPerc = rightPerc;

//         // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
//         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

//         m_tankDrive = subsystem;
//         addRequirements(m_tankDrive);

//         // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
//     }

//     // Called when the command is initially scheduled.
//     @Override
//     public void initialize() {
//         WPI_TalonSRX frontLeft = m_tankDrive.getFrontLeft();
//         WPI_TalonSRX backLeft = m_tankDrive.getBackLeft();
//         WPI_TalonSRX frontRight = m_tankDrive.getFrontRight();
//         WPI_TalonSRX backRight = m_tankDrive.getBackRight();

//         frontLeft.set(m_leftPerc);
//         backLeft.set(m_leftPerc);
//         frontRight.set(m_rightPerc);
//         backRight.set(m_rightPerc);
//     }

//     // Called every time the scheduler runs while the command is scheduled.
//     @Override
//     public void execute() {
//     }

//     // Called once the command ends or is interrupted.
//     @Override
//     public void end(boolean interrupted) {
//     }

//     // Returns true when the command should end.
//     @Override
//     public boolean isFinished() {
//         return true;
//     }

//     @Override
//     public boolean runsWhenDisabled() {
//         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
//         return false;

//         // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
//     }
// }

